#!/bin/bash
###############################################################################
# #2150 -- iccApply* clipped a PCS source carrying icEncodeUnitFloat
###############################################################################
#
# Both tools remap a PCS source signature to a device one before converting,
# so that PCS-encoded numbers are not reinterpreted as device data:
#
#   if (bInputProfile && IsSpacePCS(SrcspaceSig)) {     // iccApplyNamedCmm
#     if (SrcspaceSig == icSigXYZPcsData) SrcspaceSig = icSigDevXYZData;
#     else if (SrcspaceSig == icSigLabPcsData) SrcspaceSig = icSigDevLabData;
#     if (srcEncoding == icEncodeFloat) bClip = false;  // <-- one synonym only
#   }
#
# After that remap the value no longer meets ToInternalEncoding()'s 'XYZ ' or
# 'Lab ' arm; it meets the shared device default:, whose float case clips to
# 0.0-1.0 whenever bClip. #2146 made icEncodeUnitFloat an exact synonym of
# icEncodeFloat in both PCS arms, but the carve-out above named only one of the
# two -- so the selector, and nothing else, decided whether the data survived.
#
# Measured on 78a781e8 before the fix, iccApplyNamedCmm against an XYZ PCS
# profile, the same three numbers in and only the selector changed:
#
#   icEncodeUnitFloat  1.8 1.9 1.7  ->  0.9999  1.0000  1.0003   (saturated)
#   icEncodeFloat      1.8 1.9 1.7  ->  1.7999  1.9000  1.7004   (correct)
#
# The external PCS float range runs to ~2.0 because icXyzFromPcs scales by
# 65535/32768, so the clip discarded legitimate values rather than hardening
# anything -- the same reasoning that kept the library's PCS arms unclipped in
# #2146. The fix names both synonyms in both tools.
#
# Environment variables:
#   ICCDEV_TOOLS_DIR   -- path to Build/Tools
#   ICCDEV_TESTING_DIR -- path to Testing
#   ICCDEV_TEST_OUTDIR -- output directory for generated logs/data files
###############################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TOOLS_DIR="${ICCDEV_TOOLS_DIR:-$REPO_ROOT/Build/Tools}"
TESTING_DIR="${ICCDEV_TESTING_DIR:-$REPO_ROOT/Testing}"
OUTDIR="${ICCDEV_TEST_OUTDIR:-/tmp/iccdev-issue-2150-pcs-unitfloat-clip}"
mkdir -p "$OUTDIR"

if [ ! -d "$TOOLS_DIR" ]; then
  for candidate in "$REPO_ROOT/build/Tools" "$REPO_ROOT/Build/Tools" "$REPO_ROOT/build-dbg/Tools"; do
    if [ -d "$candidate" ]; then
      TOOLS_DIR="$candidate"
      break
    fi
  done
fi

BUILD_ROOT="$(cd "$TOOLS_DIR/.." 2>/dev/null && pwd -P)"
if [ -n "$BUILD_ROOT" ]; then
  export LD_LIBRARY_PATH="$BUILD_ROOT/IccProfLib:$BUILD_ROOT/IccXML:$BUILD_ROOT/IccJSON:$BUILD_ROOT/IccConnect:$BUILD_ROOT/IccConnect/IccLibConnect${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi
export ASAN_OPTIONS="${ASAN_OPTIONS:-print_scariness=1:halt_on_error=0:detect_leaks=0}"
export UBSAN_OPTIONS="${UBSAN_OPTIONS:-halt_on_error=0:print_stacktrace=1}"
export LLVM_PROFILE_FILE="${LLVM_PROFILE_FILE:-/dev/null}"

APPLY="$(find "$TOOLS_DIR" -maxdepth 2 -name iccApplyNamedCmm -type f 2>/dev/null | head -1)"
SEARCH="$(find "$TOOLS_DIR" -maxdepth 2 -name iccApplySearch -type f 2>/dev/null | head -1)"

# Both carry a PCS colour space in the profile header, which is what makes the
# tools treat the run as an input profile and take the remap branch at all. No
# tracked .icc does; these are generated by CreateAllProfiles.sh from tracked
# XML, hence the fixture dependency on the CTest.
XYZP="$TESTING_DIR/PCC/XYZ_float-D50_2deg.icc"
LABP="$TESTING_DIR/PCC/Lab_float-D50_2deg.icc"
# The device control's profile, by contrast, is tracked.
RGBP="$TESTING_DIR/sRGB_v4_ICC_preference.icc"

fail() {
  echo "  [FAIL] issue-2150-pcs-unitfloat-clip -- $1"
  exit 1
}

check_sanitizers() {
  local logfile="$1"

  if grep -qE "ERROR: AddressSanitizer|UndefinedBehaviorSanitizer|runtime error:|LeakSanitizer|DEADLYSIGNAL" "$logfile" 2>/dev/null; then
    sed -n '1,120p' "$logfile"
    return 1
  fi

  return 0
}

require_file() {
  [ -f "$1" ] || fail "missing fixture: $1"
}

require_tool() {
  [ -x "$1" ] || fail "missing executable: $1"
}

# Writes a legacy data file: one row, one space, one encoding.
write_data() {
  local path="$1" space="$2" enc="$3" values="$4"

  printf "%s ; Data Format\n%s ; Encoding\n %s\n" "$space" "$enc" "$values" > "$path"
}

run_expect_success() {
  local name="$1"
  shift
  local logfile="$OUTDIR/$name.log"
  local rc=0

  rm -f "$logfile"
  set +e
  timeout 60 "$@" > "$logfile" 2>&1
  rc=$?
  set -e

  check_sanitizers "$logfile" || fail "$name emitted sanitizer diagnostics"
  [ "$rc" -eq 124 ] && fail "$name timed out"
  if [ "$rc" -ne 0 ]; then
    sed -n '1,80p' "$logfile"
    fail "$name failed with exit=$rc"
  fi
}

# The converted-value column of the single data row.
#
# A row is a line carrying a standalone ';' field with numeric fields before it;
# those preceding fields are the converted values and the ';' stops the scan
# before the echoed source column. Requiring at least one such row is what stops
# usage output satisfying any assertion below -- Usage() prints selector lines
# like "   10 + Intent" that begin with a number but carry no ';' field.
converted_row() {
  local logfile="$1"
  local row

  row="$(awk '
    $0 ~ /;/ {
      out = ""; n = 0
      for (i = 1; i <= NF && $i != ";"; i++) {
        if ($i ~ /^[+-]?[0-9]+\.?[0-9]*$/) { out = out " " $i; n++ }
        else { n = 0; break }
      }
      if (n > 0) { print out; exit }
    }
  ' "$logfile")"

  [ -n "$row" ] || fail "no converted data row in $(basename "$logfile")"
  echo "$row"
}

assert_same_row() {
  local what="$1" a="$2" b="$3"

  if [ "$(converted_row "$OUTDIR/$a.log")" != "$(converted_row "$OUTDIR/$b.log")" ]; then
    echo "    $a: $(converted_row "$OUTDIR/$a.log")"
    echo "    $b: $(converted_row "$OUTDIR/$b.log")"
    fail "$what"
  fi
}

assert_differing_rows() {
  local what="$1" a="$2" b="$3"

  if [ "$(converted_row "$OUTDIR/$a.log")" = "$(converted_row "$OUTDIR/$b.log")" ]; then
    echo "    $a: $(converted_row "$OUTDIR/$a.log")"
    echo "    $b: $(converted_row "$OUTDIR/$b.log")"
    fail "$what"
  fi
}

# The anti-vacuity pin. Equality between two selectors is necessary but not
# sufficient: clipping *both* would satisfy it while still destroying the data,
# so every PCS case is also run with its source values clamped into the unit
# range and the two runs must differ. If the clip bites, the above-range run is
# reduced to the clamped one and they coincide.
#
# Deliberately relative rather than an absolute floor. An earlier version pinned
# "> 1.0" and passed on clipped data, because the clip bounds the *internal*
# value at 1.0 while these rows are what the transform then produced from it --
# the saturated rows measure 1.0003 and exactly 2.0000. Replacing that with a
# per-site absolute floor worked but pinned numbers that are themselves
# artifacts of the remap: the search figure of 3.5166 exists only because the
# input path skips icXyzToPcs while the output path applies icXyzFromPcs, so
# correcting that asymmetry -- a plausible follow-up to this very issue -- would
# turn the floor into a false red claiming a clip that had not happened. The
# clamped-input comparison asserts the same property and survives any change to
# what the transform computes, which is also how the 'Lab ' and device cases
# below are written.
assert_clip_did_not_bite() {
  local what="$1" above="$2" clamped="$3"

  assert_differing_rows "$what" "$above" "$clamped"
}

require_file "$XYZP"
require_file "$LABP"
require_file "$RGBP"

# Set by each tool's block once it has actually run its cases; checked at the
# end so a locate failure cannot pass as a skip.
exercised=0

echo "=== #2150 PCS icEncodeUnitFloat source clipping regression ==="

###############################################################################
# iccApplyNamedCmm
###############################################################################

if [ -n "$APPLY" ]; then
  require_tool "$APPLY"

  # 'XYZ ' PCS source. An internal 0.9 leaves the destination side as ~1.8, so
  # these are the numbers a preceding icEncodeUnitFloat run legitimately writes
  # and this one must be able to read back. The 1.0 variant is the clamped
  # control the anti-vacuity pin compares against.
  write_data "$OUTDIR/xyz-unit.txt"    "'XYZ '" icEncodeUnitFloat "1.79997 1.89997 1.69997"
  write_data "$OUTDIR/xyz-float.txt"   "'XYZ '" icEncodeFloat     "1.79997 1.89997 1.69997"
  write_data "$OUTDIR/xyz-unit-at.txt" "'XYZ '" icEncodeUnitFloat "1.0 1.0 1.0"

  run_expect_success xyz-unit-namedcmm    "$APPLY" "$OUTDIR/xyz-unit.txt"    3 0 "$XYZP" 1
  run_expect_success xyz-float-namedcmm   "$APPLY" "$OUTDIR/xyz-float.txt"   3 0 "$XYZP" 1
  run_expect_success xyz-unit-at-namedcmm "$APPLY" "$OUTDIR/xyz-unit-at.txt" 3 0 "$XYZP" 1
  exercised=1

  assert_clip_did_not_bite \
    "iccApplyNamedCmm: an 'XYZ ' icEncodeUnitFloat source above 1.0 was clamped to 1.0" \
    xyz-unit-namedcmm xyz-unit-at-namedcmm
  assert_same_row \
    "iccApplyNamedCmm: an 'XYZ ' PCS source must convert identically under icEncodeUnitFloat and icEncodeFloat" \
    xyz-unit-namedcmm xyz-float-namedcmm

  # icEncodePercent is the third encoding whose PCS range exceeds 0.0-1.0 -- the
  # same range x100 -- and the device default: arm clips it for exactly the same
  # reason. It is asserted against the icEncodeFloat run rather than by scale,
  # because 179.997 percent and 1.79997 float denote the *same* internal value,
  # so the two must convert to the same row. Pre-fix the percent run saturates
  # to 0.9999 1.0000 1.0003 while the float control returns 1.7999 1.9000
  # 1.7004. 'XYZ ' only: the 'Lab ' arm rejects percent in both directions,
  # which is the #2124 contract.
  write_data "$OUTDIR/xyz-pct.txt"    "'XYZ '" icEncodePercent "179.997 189.997 169.997"
  write_data "$OUTDIR/xyz-pct-at.txt" "'XYZ '" icEncodePercent "100.0 100.0 100.0"

  run_expect_success xyz-pct-namedcmm    "$APPLY" "$OUTDIR/xyz-pct.txt"    3 0 "$XYZP" 1
  run_expect_success xyz-pct-at-namedcmm "$APPLY" "$OUTDIR/xyz-pct-at.txt" 3 0 "$XYZP" 1

  assert_clip_did_not_bite \
    "iccApplyNamedCmm: an 'XYZ ' icEncodePercent source above 100.0 was clamped to 100.0" \
    xyz-pct-namedcmm xyz-pct-at-namedcmm
  assert_same_row \
    "iccApplyNamedCmm: 179.997 percent and 1.79997 float are the same internal value and must convert alike" \
    xyz-pct-namedcmm xyz-float-namedcmm

  # 'Lab ' PCS source. Its external range does not reach ~2.0 the way XYZ's
  # does, so the clip only bites above L*=100 -- measured, not assumed: the two
  # runs below must stay distinguishable, which they cannot be if 1.5 is
  # clamped to 1.0. This is what stops the fix being read as XYZ-only when the
  # remap branch it lives in serves both PCS spaces.
  write_data "$OUTDIR/lab-unit-over.txt"  "'Lab '" icEncodeUnitFloat "1.5 0.48 0.55"
  write_data "$OUTDIR/lab-float-over.txt" "'Lab '" icEncodeFloat     "1.5 0.48 0.55"
  write_data "$OUTDIR/lab-unit-at.txt"    "'Lab '" icEncodeUnitFloat "1.0 0.48 0.55"

  run_expect_success lab-unit-over-namedcmm  "$APPLY" "$OUTDIR/lab-unit-over.txt"  3 0 "$LABP" 1
  run_expect_success lab-float-over-namedcmm "$APPLY" "$OUTDIR/lab-float-over.txt" 3 0 "$LABP" 1
  run_expect_success lab-unit-at-namedcmm    "$APPLY" "$OUTDIR/lab-unit-at.txt"    3 0 "$LABP" 1

  assert_same_row \
    "iccApplyNamedCmm: a 'Lab ' PCS source must convert identically under icEncodeUnitFloat and icEncodeFloat" \
    lab-unit-over-namedcmm lab-float-over-namedcmm
  assert_clip_did_not_bite \
    "iccApplyNamedCmm: a 'Lab ' icEncodeUnitFloat source above 1.0 was clamped to 1.0" \
    lab-unit-over-namedcmm lab-unit-at-namedcmm

  ###########################################################################
  # The device control: the carve-out must NOT have widened
  #
  # bClip is cleared only inside the PCS remap branch, so a device source never
  # reaches it and must still clip. Asserted by equality with a hand-clamped
  # input rather than against a literal, so it stays valid whatever the profile
  # transform does with the clamped values.
  ###########################################################################

  write_data "$OUTDIR/rgb-unit-over.txt" "'RGB '" icEncodeUnitFloat "1.5 -0.5 0.5"
  write_data "$OUTDIR/rgb-unit-at.txt"   "'RGB '" icEncodeUnitFloat "1.0 0.0 0.5"

  run_expect_success rgb-unit-over-namedcmm "$APPLY" "$OUTDIR/rgb-unit-over.txt" 3 0 "$RGBP" 1
  run_expect_success rgb-unit-at-namedcmm   "$APPLY" "$OUTDIR/rgb-unit-at.txt"   3 0 "$RGBP" 1

  assert_same_row \
    "iccApplyNamedCmm: a device icEncodeUnitFloat source must still clip to 0.0-1.0" \
    rgb-unit-over-namedcmm rgb-unit-at-namedcmm
else
  echo "  [SKIP] iccApplyNamedCmm not built"
fi

###############################################################################
# iccApplySearch
#
# Fixed in the same commit because the two tools carry independent copies of
# the remap block rather than sharing a helper -- so this half would not follow
# from the one above. It needs two profiles and -INIT, and applying the same
# PCS profile twice keeps the case about the source conversion rather than
# about any particular transform.
###############################################################################

if [ -n "$SEARCH" ]; then
  require_tool "$SEARCH"

  write_data "$OUTDIR/xyz-unit-search.txt"    "'XYZ '" icEncodeUnitFloat "1.79997 1.89997 1.69997"
  write_data "$OUTDIR/xyz-float-search.txt"   "'XYZ '" icEncodeFloat     "1.79997 1.89997 1.69997"
  write_data "$OUTDIR/xyz-unit-at-search.txt" "'XYZ '" icEncodeUnitFloat "1.0 1.0 1.0"

  run_expect_success xyz-unit-search \
    "$SEARCH" "$OUTDIR/xyz-unit-search.txt"    3 0 "$XYZP" 1 "$XYZP" 1 -INIT 1
  run_expect_success xyz-float-search \
    "$SEARCH" "$OUTDIR/xyz-float-search.txt"   3 0 "$XYZP" 1 "$XYZP" 1 -INIT 1
  run_expect_success xyz-unit-at-search \
    "$SEARCH" "$OUTDIR/xyz-unit-at-search.txt" 3 0 "$XYZP" 1 "$XYZP" 1 -INIT 1
  exercised=1

  assert_clip_did_not_bite \
    "iccApplySearch: an 'XYZ ' icEncodeUnitFloat source above 1.0 was clamped to 1.0" \
    xyz-unit-search xyz-unit-at-search
  assert_same_row \
    "iccApplySearch: an 'XYZ ' PCS source must convert identically under icEncodeUnitFloat and icEncodeFloat" \
    xyz-unit-search xyz-float-search
else
  echo "  [SKIP] iccApplySearch not built"
fi

# CMake registers this test when at least one of the two targets exists, so
# reaching here having exercised neither means the binaries were not located --
# a build-layout change defeating the find above, or the .exe suffix on a
# Windows runner. Without this, that case reported [PASS] having asserted
# nothing, which is the failure mode the whole file exists to catch.
if [ "$exercised" -eq 0 ]; then
  fail "neither iccApplyNamedCmm nor iccApplySearch was located under $TOOLS_DIR -- nothing was asserted"
fi

echo "  [PASS] issue-2150-pcs-unitfloat-clip"
exit 0
