// Regression test for the one-level per-tag load that
// MyChild::OnTagClicked (Tools/wxWidget/wxProfileDump/wxProfileDump.cpp) uses
// to open an embeddedV5ProfileTag ('ICC5', tag type 'ICCp') in its own
// profile window.
//
// This used to be:
//
//     if (pEmbed->ReadAll() && pEmbed->GetProfile()) {
//       CIccProfile *pCopy = pEmbed->GetProfile()->NewCopy();
//       ... hand pCopy to a new window, which owns and frees it ...
//     }
//
// ReadAll() pulls the *entire* nested tree of embedded profiles. The depth
// guard in CIccTagEmbeddedProfile::Read (IccProfLib/IccTagEmbedIcc.cpp:218)
// does not bound that path: LoadTag (IccProfLib/IccProfile.cpp:1431-1441)
// lets Read() return -- destroying that call's guard -- before calling
// ReadAll(), so the guard's counter unwinds at every level while the C++
// stack keeps growing. Measured cost is roughly O(depth^2.7): a 90 KB
// crafted profile (depth 250) freezes the GUI for 2.3s, depth 1000 (180 KB)
// for 95.7s, and depth 2000 (359 KB) for over ten minutes -- with no
// progress indicator and no cancel. wxProfileDump exists to inspect
// profiles you do not trust, so this is reachable by design.
//
// The fix loads exactly one level, per tag:
//
//     std::vector<icTagSignature> sigs;
//     for (i = pInner->m_Tags.begin(); i != pInner->m_Tags.end(); ++i)
//       sigs.push_back((icTagSignature)i->TagInfo.sig);
//     for (n = 0; n < sigs.size(); n++)
//       (void)pInner->FindTag(sigs[n]);
//
// FindTag goes through LoadTag with bReadAll=false, so a nested embedded
// profile is Attach()ed but never descended into. Cost is flat in nesting
// depth (86ms at depth 2000) and the depth guard becomes irrelevant instead
// of needing a fix. If nothing loads (nLoaded == 0 after the loop --
// precisely the state a profile nested two levels deep is in, since it is
// reached through an already-copied profile with no IO) OnTagClicked falls
// through to the existing MyTagDialog text dump instead of opening a window
// with an empty tag list.
//
// This test guards four things, none of which are exercised anywhere else
// in the regression suite:
//
// 1. ORDERING (fixture): before any load, a profile's tag directory exists
//    (Attach() read it) but nothing in it is loaded, and NewCopy() taken at
//    that point carries the full directory with every entry's pTag NULL.
// 2. POPULATION (fixture): the one-level per-tag FindTag loop loads every
//    one of the *inner* profile's own tags, and a fresh NewCopy() taken
//    afterwards carries them too -- the state the GUI hands to the new
//    window.
// 3. INDEPENDENCE (fixture): the copy shares no tag-pointer identity with
//    the parent, and stays readable after the parent is freed -- mirrors
//    the GUI closing the outer window while the embedded one stays open.
// 4. ONE LEVEL ONLY, and the fallback trigger (in-memory, no fixture
//    needed): the per-tag loop on a profile that itself carries a nested
//    embeddedV5ProfileTag must NOT descend into that nested profile -- its
//    tags must stay unloaded. And: NewCopy()'d, the nested profile reached
//    through the copy has no IO and loads zero tags even if the same
//    per-tag loop is retried against it -- this is the nLoaded == 0
//    condition OnTagClicked's fallback guard depends on.
//
// Fixture (used by checks 1-3 only): Testing/hybrid/ICC/CMYK_Hybrid_Profile.icc.
// This is NOT tracked -- it is generated by Testing/hybrid/BuildAndTest.sh
// (via iccFromXml) from the tracked Testing/hybrid/CMYK_Hybrid_Profile.xml,
// and Testing/hybrid/.gitignore excludes ICC/*.icc. It carries exactly one
// embeddedV5ProfileTag (confirmed via iccDumpProfile: offset 2684968, size
// 1004012), whose inner v5 profile has 6 tags (D2B3, swpt, svcn, c2sp, s2cp,
// cprt -- notably no profileDescriptionTag, unlike some other hybrid
// fixtures, so this test uses copyrightTag as its representative tag) and,
// per that same dump, no further nested embedded tag -- which is exactly why
// check 4 needs an in-memory profile instead: this fixture cannot exercise
// "one level only".  The outer profile is opened the same way wxProfileDump
// opens files -- via OpenIccProfile(), which defers tag loading -- so the
// embedded tag really is in the "attached but not read" state when FindTag()
// first returns it.
//
// The fixture is not produced on every CI leg (macOS runs "CreateAllProfiles
// only"; Windows has no hybrid step; even the Linux hybrid step tolerates its
// own failure), so its absence is not itself a regression. Checks 1-3 run
// only when the fixture is present; check 4 needs no fixture at all and
// always runs, so a corpus change cannot silently disable it. This test
// tells the two fixture cases apart deliberately:
//   - fixture file does not exist   -> SKIP, exit 77 (ctest SKIP_RETURN_CODE),
//                                       but only after check 4 has already
//                                       run and passed
//   - fixture exists but is broken  -> FAIL, exit 1 (never laundered into a skip)
//
// Exit code: 0 = pass, 77 = skipped (fixture not generated, in-memory checks
// still passed), other non-zero = fail.

#include "IccProfile.h"
#include "IccTag.h"
#include "IccTagBasic.h"
#include "IccTagEmbedIcc.h"
#include "IccUtil.h"
#include "icProfileHeader.h"

#include <cstdio>
#include <set>
#include <string>
#include <vector>

static const char *kFixtureProfile = "Testing/hybrid/ICC/CMYK_Hybrid_Profile.icc";

static const int kSkipReturnCode = 77;

static int g_failures = 0;

static void check(bool bCondition, const char *szMessage)
{
  if (bCondition) {
    std::printf("ok:   %s\n", szMessage);
  }
  else {
    std::printf("FAIL: %s\n", szMessage);
    g_failures++;
  }
}

// Count total tag-directory entries and how many of them already carry a
// loaded tag object (entry.pTag != NULL). m_Tags is public; m_TagVals (the
// loaded-tag list itself) is protected, so entry.pTag is the correct public
// way to tell loaded tags from directory-only entries.
static void countTagEntries(const CIccProfile *pProfile, size_t &nTotal, size_t &nLoaded)
{
  nTotal = 0;
  nLoaded = 0;
  for (TagEntryList::const_iterator i = pProfile->m_Tags.begin();
       i != pProfile->m_Tags.end(); ++i) {
    nTotal++;
    if (i->pTag)
      nLoaded++;
  }
}

// Collect the identity (address) of pProfile itself and every loaded tag
// object reachable from its public m_Tags directory. Used to prove a copy
// aliases nothing in the profile it was copied from, by address rather than
// by dereferencing anything -- so the check is meaningful even without ASan.
static void collectIdentities(const CIccProfile *pProfile, std::set<const void*> &identities)
{
  identities.insert((const void*)pProfile);
  for (TagEntryList::const_iterator i = pProfile->m_Tags.begin();
       i != pProfile->m_Tags.end(); ++i) {
    if (i->pTag)
      identities.insert((const void*)i->pTag);
  }
}

// The one-level per-tag load itself -- copied verbatim (in spirit) from
// MyChild::OnTagClicked's loop. Collect signatures first, then load: LoadTag
// mutates m_Tags entries in place, so calling FindTag while iterating m_Tags
// is not safe.
//
// To verify this test actually bites (see task-4-report.md Step 4), the call
// sites below were temporarily changed to call ReadAll() on the owning
// CIccTagEmbeddedProfile tag instead of this function, which recursively
// loads every level and made the "one level only" check FAIL as expected.
static void findAllTagsOneLevel(CIccProfile *pProfile)
{
  std::vector<icTagSignature> sigs;
  TagEntryList::iterator i;
  for (i = pProfile->m_Tags.begin(); i != pProfile->m_Tags.end(); ++i)
    sigs.push_back((icTagSignature)i->TagInfo.sig);

  for (size_t n = 0; n < sigs.size(); n++)
    (void)pProfile->FindTag(sigs[n]);
}

// ---------------------------------------------------------------------------
// Helpers for building an in-memory nested embedded profile, adapted from
// out/scratch-nestdepth/nestdepth.cpp (a gitignored measurement harness, not
// part of the repo).
// ---------------------------------------------------------------------------

static void initHeader(CIccProfile *p)
{
  p->m_Header.deviceClass = icSigAbstractClass;
  p->m_Header.colorSpace  = icSigLabData;
  p->m_Header.pcs         = icSigLabData;
  p->m_Header.version     = icVersionNumberV5;
  p->m_Header.magic       = icMagicNumber;
  p->m_Header.platform    = icSigMicrosoft;
  p->m_Header.renderingIntent = icPerceptual;
  p->m_Header.illuminant.X = 0x0000f6d6;
  p->m_Header.illuminant.Y = 0x00010000;
  p->m_Header.illuminant.Z = 0x0000d32d;
}

static CIccTagText *makeText(const char *s)
{
  CIccTagText *p = new CIccTagText();
  p->SetText(s);
  return p;
}

// Innermost profile: small but non-empty, and carries no embedded tag of its
// own -- this is the leaf that must stay unread by a one-level load two
// hops up.
static CIccProfile *makeLeaf()
{
  CIccProfile *p = new CIccProfile();
  initHeader(p);
  p->AttachTag(icSigCopyrightTag, makeText("leaf"));
  return p;
}

// Wrap pInner in a new profile carrying it as an embeddedV5ProfileTag, plus
// its own copyrightTag so ordinary sibling tags are distinguishable from the
// nested embedded one.
static CIccProfile *wrap(CIccProfile *pInner, int level)
{
  CIccProfile *p = new CIccProfile();
  initHeader(p);

  char buf[64];
  std::snprintf(buf, sizeof(buf), "level-%d", level);
  p->AttachTag(icSigCopyrightTag, makeText(buf));

  CIccTagEmbeddedProfile *pEmbed = new CIccTagEmbeddedProfile();
  pEmbed->SetProfile(pInner); // takes ownership
  p->AttachTag(icSigEmbeddedV5ProfileTag, pEmbed);

  return p;
}

// Find pProfile's own loaded embeddedV5ProfileTag object, if any, by walking
// m_Tags directly rather than calling FindTag a second time. FindTag only
// calls LoadTag when entry.pTag is NULL (CIccProfile::FindTag(IccTagEntry&),
// IccProfLib/IccProfile.cpp:436-441), so a second FindTag call on an
// already-loaded entry is actually a harmless no-op here -- but walking
// m_Tags is what OnTagClicked's own loop does, and keeps this check
// independent of that FindTag guarantee.
static CIccTagEmbeddedProfile *findLoadedEmbeddedTag(CIccProfile *pProfile)
{
  for (TagEntryList::iterator i = pProfile->m_Tags.begin(); i != pProfile->m_Tags.end(); ++i) {
    if (i->TagInfo.sig == icSigEmbeddedV5ProfileTag && i->pTag &&
        i->pTag->GetType() == icSigEmbeddedProfileType) {
      return (CIccTagEmbeddedProfile*)i->pTag;
    }
  }
  return NULL;
}

// ---------------------------------------------------------------------------
// Check 4: one level only, and the fallback trigger. In-memory, no fixture.
// ---------------------------------------------------------------------------
static int runNestedInMemoryChecks(const char *szScratchPath)
{
  std::printf("--- in-memory nested-profile checks (no fixture needed) ---\n");

  // Two levels of embedding: pTop -> embeddedV5ProfileTag -> pMid ->
  // embeddedV5ProfileTag -> pLeaf. A one-level load reached through pTop
  // loads pMid's own tags (including the tag object for its nested
  // embedded profile) but must not go on to load pLeaf's tags.
  CIccProfile *pLeaf = makeLeaf();
  CIccProfile *pMid  = wrap(pLeaf, 0);
  CIccProfile *pTop  = wrap(pMid, 1);

  bool bSaved = SaveIccProfile(szScratchPath, pTop);
  delete pTop; // owns pMid, which owns pLeaf
  pTop = NULL;
  pMid = NULL;
  pLeaf = NULL;

  check(bSaved, "in-memory 2-level nested profile saves to a scratch file");
  if (!bSaved) {
    std::printf("\n%d check(s) FAILED -- cannot continue without the nested scratch profile\n", g_failures);
    return 1;
  }

  CIccProfile *pOuter = OpenIccProfile(szScratchPath);
  check(pOuter != NULL, "nested scratch profile re-opens (lazily, like wxProfileDump does)");
  if (!pOuter) {
    std::printf("\n%d check(s) FAILED\n", g_failures);
    return 1;
  }

  CIccTag *pTag = pOuter->FindTag(icSigEmbeddedV5ProfileTag);
  check(pTag != NULL && pTag->GetType() == icSigEmbeddedProfileType,
        "outer profile carries an embeddedV5ProfileTag identifying CIccTagEmbeddedProfile");
  if (!pTag || pTag->GetType() != icSigEmbeddedProfileType) {
    delete pOuter;
    std::printf("\n%d check(s) FAILED\n", g_failures);
    return 1;
  }

  CIccTagEmbeddedProfile *pEmbed = (CIccTagEmbeddedProfile*)pTag;
  CIccProfile *pInner = pEmbed->GetProfile(); // pMid, attached but unread
  check(pInner != NULL, "outer's embedded tag carries an inner profile object (pMid)");
  if (!pInner) {
    delete pOuter;
    std::printf("\n%d check(s) FAILED\n", g_failures);
    return 1;
  }

  size_t nTotal0 = 0, nLoaded0 = 0;
  countTagEntries(pInner, nTotal0, nLoaded0);
  check(nTotal0 == 2, "pMid's tag directory carries both its own tags before any load");
  check(nLoaded0 == 0, "nothing in pMid is loaded yet (Attach-only, the state OnTagClicked starts from)");

  // The one-level FindTag load -- exactly the loop MyChild::OnTagClicked runs.
  findAllTagsOneLevel(pInner);

  size_t nTotal1 = 0, nLoaded1 = 0;
  countTagEntries(pInner, nTotal1, nLoaded1);
  check(nTotal1 == nTotal0, "the one-level load does not change pMid's tag directory size");
  check(nLoaded1 == nTotal1, "the one-level load loads every one of pMid's own tags");

  // --- ONE LEVEL ONLY -----------------------------------------------------
  CIccTagEmbeddedProfile *pNestedEmbed = findLoadedEmbeddedTag(pInner);
  check(pNestedEmbed != NULL,
        "pMid's own embeddedV5ProfileTag (-> pLeaf) loaded as part of the one-level pass");

  if (pNestedEmbed) {
    CIccProfile *pNestedInner = pNestedEmbed->GetProfile(); // pLeaf, reached through pMid
    check(pNestedInner != NULL, "pMid's nested embedded tag still carries an inner profile object (pLeaf)");
    if (pNestedInner) {
      size_t nTotalNested = 0, nLoadedNested = 0;
      countTagEntries(pNestedInner, nTotalNested, nLoadedNested);
      check(nTotalNested > 0, "pLeaf's tag directory exists (Attach() read the directory)");
      check(nLoadedNested == 0,
            "ONE LEVEL ONLY: none of pLeaf's tags are loaded -- the one-level FindTag "
            "pass on pMid must not have descended into pLeaf. (Substituting ReadAll() "
            "for the FindTag loop here is what this check is meant to catch.)");
    }
  }

  // --- the fallback trigger ------------------------------------------------
  // NewCopy() the one-level-loaded pMid, exactly as OnTagClicked does, and
  // confirm the nested profile reached through that COPY carries zero
  // loaded tags and no IO. That is precisely the nLoaded == 0 state that
  // makes OnTagClicked fall through to the tag dump for a second level, and
  // retrying the same per-tag loop against it must still load nothing.
  CIccProfile *pCopy = pInner->NewCopy();
  check(pCopy != NULL, "NewCopy() of the one-level-loaded pMid succeeds");
  if (pCopy) {
    size_t nTotalCopy = 0, nLoadedCopy = 0;
    countTagEntries(pCopy, nTotalCopy, nLoadedCopy);
    check(nTotalCopy == nTotal1, "the copy carries pMid's full tag directory");
    check(nLoadedCopy == nTotal1, "the copy carries every one of pMid's own loaded tags");

    CIccTag *pCopyRepresentative = NULL;
    for (TagEntryList::iterator i = pCopy->m_Tags.begin(); i != pCopy->m_Tags.end(); ++i) {
      if (i->TagInfo.sig == icSigCopyrightTag) {
        pCopyRepresentative = i->pTag;
        break;
      }
    }
    check(pCopyRepresentative != NULL,
          "a representative tag (copyrightTag) is retrievable from the copy -- "
          "the populated copy OnTagClicked hands to the new window");

    CIccTagEmbeddedProfile *pNestedEmbedInCopy = findLoadedEmbeddedTag(pCopy);
    check(pNestedEmbedInCopy != NULL, "the copy carries its own nested embeddedV5ProfileTag object");

    if (pNestedEmbedInCopy) {
      CIccProfile *pNestedInnerInCopy = pNestedEmbedInCopy->GetProfile();
      check(pNestedInnerInCopy != NULL,
            "the copy's nested embedded tag still carries an inner profile object");
      if (pNestedInnerInCopy) {
        check(!pNestedInnerInCopy->HasIO(),
              "FALLBACK TRIGGER: the nested profile reached through the copy has no IO "
              "-- NewCopy() severs the attachment, so nothing can be read from it");

        size_t nTotalNC = 0, nLoadedNC = 0;
        countTagEntries(pNestedInnerInCopy, nTotalNC, nLoadedNC);
        check(nLoadedNC == 0,
              "FALLBACK TRIGGER: none of the copy's nested tags are loaded before retrying the load");

        // Retry the same one-level loop OnTagClicked would run for a second
        // level, against the copy's nested profile. With no IO, this must
        // load nothing -- nLoaded == 0 is exactly the condition
        // OnTagClicked's guard uses to fall through to MyTagDialog instead
        // of opening an empty window.
        findAllTagsOneLevel(pNestedInnerInCopy);

        size_t nTotalNC2 = 0, nLoadedNC2 = 0;
        countTagEntries(pNestedInnerInCopy, nTotalNC2, nLoadedNC2);
        check(nTotalNC2 == nTotalNC,
              "retrying the load does not change the copy's nested tag directory size");
        check(nLoadedNC2 == 0,
              "FALLBACK TRIGGER CONFIRMED: retrying the one-level load against the copy's "
              "nested profile still loads zero tags -- this is the nLoaded==0 case "
              "OnTagClicked falls through to the tag dump for");
      }
    }

    delete pCopy;
  }

  delete pOuter; // frees pMid, pLeaf, and everything loaded into them
  std::remove(szScratchPath);

  return 0; // caller inspects g_failures
}

// ---------------------------------------------------------------------------
// Checks 1-3: ordering, population, independence. Fixture-based, skippable.
// ---------------------------------------------------------------------------
static int runFixtureChecks()
{
  // Distinguish "fixture not generated" (legitimate on several CI legs) from
  // "fixture generated but broken" (never acceptable) before trying to parse
  // it as a profile, so a present-but-corrupt fixture cannot be laundered
  // into a skip.
  FILE *pProbe = std::fopen(kFixtureProfile, "rb");
  if (!pProbe) {
    std::printf("SKIP: %s not generated (run Testing/hybrid/BuildAndTest.sh)\n", kFixtureProfile);
    return kSkipReturnCode;
  }
  std::fclose(pProbe);

  std::printf("--- fixture-based checks (%s) ---\n", kFixtureProfile);

  CIccProfile *pOuter = OpenIccProfile(kFixtureProfile);
  if (!pOuter) {
    std::printf("FAIL: %s exists but could not be opened as an ICC profile\n", kFixtureProfile);
    return 1;
  }

  CIccTag *pTag = pOuter->FindTag(icSigEmbeddedV5ProfileTag);
  check(pTag != NULL, "outer profile carries an embeddedV5ProfileTag");
  check(pTag && pTag->GetType() == icSigEmbeddedProfileType,
        "the tag's type identifies it as CIccTagEmbeddedProfile");

  if (g_failures) {
    std::printf("\n%d check(s) FAILED -- fixture does not match expectations\n", g_failures);
    delete pOuter;
    return 1;
  }

  CIccTagEmbeddedProfile *pEmbed = (CIccTagEmbeddedProfile*)pTag;
  CIccProfile *pInner = pEmbed->GetProfile();
  check(pInner != NULL, "the embedded tag carries an inner profile object");
  if (!pInner) {
    std::printf("\n%d check(s) FAILED -- cannot continue without an inner profile\n", g_failures);
    delete pOuter;
    return 1;
  }

  // --- Check 1: ordering matters ----------------------------------------
  // Before any load, the inner profile's tag directory exists (Attach() read
  // it) but nothing in it is loaded yet.
  size_t nTotalBefore = 0, nLoadedBefore = 0;
  countTagEntries(pInner, nTotalBefore, nLoadedBefore);
  check(nTotalBefore > 0, "inner profile's tag directory is non-empty before any load");
  check(nLoadedBefore == 0, "no tags are loaded yet before the one-level load");

  CIccProfile *pUnreadCopy = pInner->NewCopy();
  check(pUnreadCopy != NULL, "NewCopy() succeeds even with nothing loaded");
  if (pUnreadCopy) {
    size_t nTotalCopy = 0, nLoadedCopy = 0;
    countTagEntries(pUnreadCopy, nTotalCopy, nLoadedCopy);
    check(nTotalCopy == nTotalBefore,
          "a copy taken before any load still carries the full tag directory");
    check(nLoadedCopy == 0,
          "but none of that copy's tag entries carry a loaded tag (pTag == NULL) -- "
          "this is the property that makes load-before-NewCopy() load-bearing");
    delete pUnreadCopy;
  }

  // --- Check 2: one-level load then NewCopy() gives a populated copy -----
  findAllTagsOneLevel(pInner);

  size_t nTotalAfter = 0, nLoadedAfter = 0;
  countTagEntries(pInner, nTotalAfter, nLoadedAfter);
  check(nTotalAfter == nTotalBefore, "the one-level load does not change the tag directory size");
  check(nLoadedAfter == nTotalAfter,
        "the one-level load loads every tag in this fixture's inner profile "
        "(it has no nested embedded tag of its own, so one level is also all of it)");

  CIccProfile *pLoadedCopy = pEmbed->GetProfile()->NewCopy();
  check(pLoadedCopy != NULL, "NewCopy() after the one-level load succeeds");
  if (!pLoadedCopy) {
    std::printf("\n%d check(s) FAILED -- cannot continue without a populated copy\n", g_failures);
    delete pOuter;
    return 1;
  }

  size_t nTotalLoadedCopy = 0, nLoadedLoadedCopy = 0;
  countTagEntries(pLoadedCopy, nTotalLoadedCopy, nLoadedLoadedCopy);
  check(nTotalLoadedCopy == nTotalAfter, "the populated copy carries the full tag directory");
  check(nLoadedLoadedCopy == nTotalAfter, "and every entry in it carries a loaded tag");

  // copyrightTag ('cprt') is the representative tag for THIS fixture's inner
  // profile (confirmed present via iccDumpProfile); it has no
  // profileDescriptionTag, unlike other hybrid fixtures.
  CIccTag *pCprtInCopy = pLoadedCopy->FindTag(icSigCopyrightTag);
  check(pCprtInCopy != NULL,
        "a representative tag (copyrightTag) is retrievable from the copy");

  // --- Check 3: the copy outlives the parent, and shares nothing ---------
  // Collect identities BEFORE freeing the parent: the outer profile itself,
  // every tag it owns directly (including pEmbed), the inner embedded
  // profile object, and every tag the one-level load loaded into it. None of
  // these addresses may reappear anywhere in pLoadedCopy.
  std::set<const void*> parentIdentities;
  collectIdentities(pOuter, parentIdentities);
  collectIdentities(pInner, parentIdentities);

  // This mirrors the GUI: the outer window (and everything it owns -- the
  // embedded tag, and that tag's own original inner profile) can be closed
  // while the embedded window -- built from pLoadedCopy -- stays open.
  delete pOuter;
  pOuter = NULL;
  pTag = NULL;
  pEmbed = NULL;
  pInner = NULL;
  pCprtInCopy = NULL; // now dangling -- do not touch; re-fetch from the copy below

  // Identity check: proves independence by address, without dereferencing
  // anything freed, so this is meaningful in a plain Release build with no
  // sanitizer.
  bool bCopyIsAliasFree = (parentIdentities.find((const void*)pLoadedCopy) == parentIdentities.end());
  size_t nAliasedTags = 0;
  for (TagEntryList::const_iterator i = pLoadedCopy->m_Tags.begin();
       i != pLoadedCopy->m_Tags.end(); ++i) {
    if (i->pTag && parentIdentities.find((const void*)i->pTag) != parentIdentities.end())
      nAliasedTags++;
  }
  check(bCopyIsAliasFree, "the copy object itself is not one of the freed parent's addresses");
  check(nAliasedTags == 0,
        "none of the copy's tag pointers alias a tag pointer freed with the parent");

  // Read-through-freed-memory check: weaker on its own (a plain Release build
  // may just read plausible garbage instead of crashing), but kept because
  // under ASan/LSan it still catches a use-after-free the identity check
  // above would not describe.
  size_t nDescribed = 0;
  size_t nEntries = 0;
  for (TagEntryList::const_iterator i = pLoadedCopy->m_Tags.begin();
       i != pLoadedCopy->m_Tags.end(); ++i) {
    nEntries++;
    if (i->pTag) {
      std::string sDescription;
      i->pTag->Describe(sDescription, 100);
      if (!sDescription.empty())
        nDescribed++;
    }
  }
  check(nEntries > 0, "the independent copy still has tags to walk after the parent is freed");
  check(nDescribed == nEntries,
        "every tag in the copy can still be read (Describe() succeeds) after the parent is freed");

  CIccTag *pCprtAgain = pLoadedCopy->FindTag(icSigCopyrightTag);
  check(pCprtAgain != NULL,
        "the representative tag is still retrievable from the copy after the parent is freed");

  delete pLoadedCopy;

  if (g_failures) {
    std::printf("\n%d check(s) FAILED\n", g_failures);
    return 1;
  }

  return 0;
}

int main(int argc, char **argv)
{
  const char *szScratchPath =
      (argc > 1) ? argv[1] : "iccdev-embedded-profile-onelevel-nested-scratch.icc";

  // Check 4 needs no fixture, so it runs first and unconditionally: a
  // missing fixture cannot silently disable it, and a failure here is
  // always a hard FAIL, never laundered into a skip.
  int nNestedResult = runNestedInMemoryChecks(szScratchPath);
  if (nNestedResult != 0 || g_failures) {
    std::printf("\n%d check(s) FAILED\n", g_failures);
    return 1;
  }

  // Checks 1-3 need the generated hybrid fixture; SKIP (not fail) when it is
  // simply absent, as before.
  int nFixtureResult = runFixtureChecks();
  if (nFixtureResult == kSkipReturnCode)
    return kSkipReturnCode;
  if (nFixtureResult != 0 || g_failures) {
    std::printf("\n%d check(s) FAILED\n", g_failures);
    return 1;
  }

  std::printf("\nall checks passed\n");
  return 0;
}
