/*
    File:       hdr-corpus-manifest.cpp

    Contains:   Enforces Testing/HDR/hdr-corpus-manifest.tsv - the expected
                clause 8.10 CLASSIFICATION of every fixture in Testing/HDR.

    Why this exists separately from iccdev.qa-profile-manifest: that test
    records the VALIDATION verdict, which cannot express what most of these
    fixtures were built to pin.  Failing clause 8.10.1's membership conditions
    does not make a profile invalid, so all six membership negatives validate
    `valid` and are indistinguishable there.  Without this test they assert
    nothing at all.

    The manifest is a specification, not a snapshot.  Its `purpose` column
    says what each fixture is for, and a row whose numbers change is either a
    classifier regression or a deliberate ruling that has to be re-argued in
    that column.

    Copyright (c) International Color Consortium.  See the licence at the head
    of IccProfLib for terms.
*/

#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <cmath>
#include <string>
#include <vector>
#include <map>
#include <fstream>
#include <sstream>
#include <sys/types.h>
#include <sys/stat.h>

#if defined(_WIN32)
#include <windows.h>
#else
#include <dirent.h>
#endif

#include "IccProfile.h"
#include "IccHdrProfile.h"

static int g_fail = 0;

static void failure(const std::string &fixture, const char *what,
                    const std::string &want, const std::string &got)
{
  printf("FAIL %-28s %-18s expected %-14s got %s\n",
         fixture.c_str(), what, want.c_str(), got.c_str());
  g_fail++;
}

/* icFloatNumber is float, so an exact compare fails on values like 4,92611
 * that were written out at printf's default precision.  Relative tolerance,
 * with an absolute floor so that the many legitimate zeroes compare cleanly. */
static bool closeEnough(double a, double b)
{
  double d = fabs(a - b);
  if (d <= 1e-6)
    return true;
  double m = fabs(a) > fabs(b) ? fabs(a) : fabs(b);
  return m > 0.0 && (d / m) <= 1e-5;
}

static const char *className(icHdrProfileClass c)
{
  switch (c) {
    case icHdrProfileNone:       return "none";
    case icHdrProfileConforming: return "conforming";
    case icHdrProfileHdrContent: return "hdr-content";
  }
  return "?";
}

static const char *displaySourceName(icHdrHeadroomSource s)
{
  switch (s) {
    case icHdrHeadroomNone:    return "-";
    case icHdrHeadroomDerh:    return "derh";
    case icHdrHeadroomDcvDrwl: return "dcv-drwl";
    case icHdrHeadroomDcvCrwl: return "dcv-crwl";
  }
  return "?";
}

static const char *contentSourceName(icHdrContentHeadroomSource s)
{
  switch (s) {
    case icHdrContentHeadroomNone:    return "-";
    case icHdrContentHeadroomCll:     return "cll";
    case icHdrContentHeadroomMdcv:    return "mdcv";
    case icHdrContentHeadroomDefault: return "default-1000";
  }
  return "?";
}

static std::string fmt(double v)
{
  char buf[64];
  snprintf(buf, sizeof(buf), "%g", v);
  return buf;
}

int main()
{
  const char *kManifest = "Testing/HDR/hdr-corpus-manifest.tsv";
  const char *kDir      = "Testing/HDR/";

  std::ifstream in(kManifest);
  if (!in) {
    /* The fixtures are generated by iccdev.create-profiles, but the manifest
     * is tracked, so its absence is a broken checkout rather than a skip. */
    printf("FAIL cannot open %s\n", kManifest);
    return 1;
  }

  std::map<std::string, bool> listed;
  std::string line;
  int rows = 0;

  while (std::getline(in, line)) {
    if (line.empty() || line[0] == '#')
      continue;

    std::vector<std::string> f;
    std::stringstream ss(line);
    std::string cell;
    while (std::getline(ss, cell, '\t'))
      f.push_back(cell);

    if (f.size() < 6) {
      printf("FAIL malformed row (%u fields): %s\n",
             (unsigned)f.size(), line.c_str());
      g_fail++;
      continue;
    }

    rows++;
    const std::string &name = f[0];
    listed[name] = true;

    std::string path = std::string(kDir) + name + ".icc";
    CIccProfile *pProfile = ReadIccProfile(path.c_str());
    if (!pProfile) {
      printf("FAIL %-28s cannot open %s\n", name.c_str(), path.c_str());
      g_fail++;
      continue;
    }

    icHdrProfileInfo info;
    icGetHdrProfileInfo(pProfile, info);

    if (f[1] != className(info.nClass))
      failure(name, "class", f[1], className(info.nClass));

    if (!closeEnough(atof(f[2].c_str()), (double)info.displayHeadroom))
      failure(name, "display_headroom", f[2], fmt((double)info.displayHeadroom));

    if (f[3] != displaySourceName(info.nHeadroomSource))
      failure(name, "headroom_source", f[3], displaySourceName(info.nHeadroomSource));

    if (!closeEnough(atof(f[4].c_str()), (double)info.contentHeadroom))
      failure(name, "content_headroom", f[4], fmt((double)info.contentHeadroom));

    if (f[5] != contentSourceName(info.nContentHeadroomSource))
      failure(name, "content_source", f[5], contentSourceName(info.nContentHeadroomSource));

    delete pProfile;
  }

  /* An unlisted fixture is a failure, not a pass.  Adding a fixture without a
   * row here is exactly how a corpus drifts into asserting nothing, which is
   * the condition this file was written to end. */
  int unlisted = 0;
  {
    std::vector<std::string> found;

#if defined(_WIN32)
    WIN32_FIND_DATAA fd;
    HANDLE h = FindFirstFileA("Testing\\HDR\\*.icc", &fd);
    if (h != INVALID_HANDLE_VALUE) {
      do {
        if (!(fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY))
          found.push_back(fd.cFileName);
      } while (FindNextFileA(h, &fd));
      FindClose(h);
    }
#else
    DIR *d = opendir("Testing/HDR");
    if (d) {
      struct dirent *e;
      while ((e = readdir(d)) != NULL)
        found.push_back(e->d_name);
      closedir(d);
    }
#endif

    for (size_t i = 0; i < found.size(); i++) {
      const std::string &fn = found[i];
      if (fn.size() < 5 || fn.compare(fn.size() - 4, 4, ".icc") != 0)
        continue;
      std::string base = fn.substr(0, fn.size() - 4);
      if (listed.find(base) == listed.end()) {
        printf("FAIL %-28s built by mkprofiles but has no manifest row\n", base.c_str());
        unlisted++;
        g_fail++;
      }
    }
  }

  printf("hdr-corpus-manifest: %d rows checked, %d unlisted, %d failures\n",
         rows, unlisted, g_fail);

  if (rows == 0) {
    printf("FAIL manifest contained no rows\n");
    return 1;
  }

  return g_fail ? 1 : 0;
}
