/*
* The ICC Software License, Version 0.2
*
*
* Copyright (c) 2003-2012 The International Color Consortium. All rights
* reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
*
* 1. Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
* 2. Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in
*    the documentation and/or other materials provided with the
*    distribution.
*
* 3. In the absence of prior written permission, the names "ICC" and "The
*    International Color Consortium" must not be used to imply that the
*    ICC organization endorses or promotes products derived from this
*    software.
*
*
* THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
* WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED.  IN NO EVENT SHALL THE INTERNATIONAL COLOR CONSORTIUM OR
* ITS CONTRIBUTING MEMBERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
* LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
* USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
* ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
* OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
* SUCH DAMAGE.
* ====================================================================
*
* This software consists of voluntary contributions made by many
* individuals on behalf of the The International Color Consortium.
*
*
* Membership in the ICC is encouraged when this software is used for
* commercial purposes.
*
*
* For more information on The International Color Consortium, please
* see <http://www.color.org/>.
*
*
*/

/*
    File:       pcs-adjust-placement.cpp

    Contains:   Characterization tests for PCS adjustment placement.

    A PCS adjustment (absolute media-white scaling, the v2-perceptual black
    point shift) is applied either by CIccPcsXform or inside CIccXform::Apply,
    depending on where the transform sits in the chain. This file pins what the
    adjustment *does*, so that moving *where* it happens is provably behaviour
    preserving.

    Tolerance: assertions use 1e-5 relative. The adjustments under test are
    ~3.5e-3 (v2 perceptual) or larger (absolute); re-associating the same affine
    math into CIccPcsSteps moves results by ~1e-7. Bit-equality is the wrong
    oracle and would fail on correct code.
*/

#include "IccCmm.h"
#include "IccDefs.h"
#include "IccProfile.h"
#include "IccTag.h"
#include "IccTagBasic.h"
#include "IccTagLut.h"

#include <cmath>
#include <cstdio>

static int g_failures = 0;

static void check(bool cond, const char *msg)
{
  if (cond) {
    std::printf("ok:   %s\n", msg);
  }
  else {
    std::printf("FAIL: %s\n", msg);
    ++g_failures;
  }
}

// Relative comparison with an absolute floor, so values near zero do not
// demand impossible precision.
static bool closeRel(double got, double want, double tol)
{
  const double diff = std::fabs(got - want);
  const double scale = std::fabs(want) > 1.0 ? std::fabs(want) : 1.0;
  return diff / scale <= tol;
}

static const double kTol = 1e-5;

// --- fixtures -------------------------------------------------------------
// Built in memory rather than read from Testing/*.icc: Testing/**/*.icc is
// gitignored and generated by CreateAllProfiles.sh, so a tracked fixture is not
// available on a fresh clone.

static void attachRequiredTags(CIccProfile &profile, const char *desc)
{
  CIccTagTextDescription *pDesc = new CIccTagTextDescription();
  pDesc->SetText(desc);
  profile.AttachTag(icSigProfileDescriptionTag, pDesc);

  CIccTagText *pCprt = new CIccTagText();
  pCprt->SetText("Copyright (C) 2026 The International Color Consortium");
  profile.AttachTag(icSigCopyrightTag, pCprt);

  // Deliberately NOT the D50 illuminant. The absolute-intent adjustment is
  // driven by (mediaWhite != illuminant); a D50 media white would make the
  // absolute cases silently no-ops and the test would prove nothing.
  CIccTagXYZ *pWtpt = new CIccTagXYZ(1);
  (*pWtpt)[0].X = icDtoF((icFloatNumber)0.9000);
  (*pWtpt)[0].Y = icDtoF((icFloatNumber)0.9500);
  (*pWtpt)[0].Z = icDtoF((icFloatNumber)0.7500);
  profile.AttachTag(icSigMediaWhitePointTag, pWtpt);
}

// A smooth CMYK -> Lab cell. Values are PCS-encoded 0..1.
static void cmykToLabCell(const double *in, icFloatNumber *out)
{
  const double k = in[3];
  const double lum = (1.0 - k) * (1.0 - 0.30 * in[0] - 0.20 * in[1] - 0.10 * in[2]);
  out[0] = (icFloatNumber)(lum < 0.0 ? 0.0 : lum);            // L* 0..1
  out[1] = (icFloatNumber)(0.5 + 0.25 * (in[0] - in[1]));     // a* offset-encoded
  out[2] = (icFloatNumber)(0.5 + 0.25 * (in[1] - in[2]));     // b* offset-encoded
}

// A rough inverse of the above. It does not have to invert exactly -- every
// assertion in this file compares two chains built from the *same* CLUTs, so
// LUT round-trip error cancels and only the PCS adjustment can differ.
static void labToCmykCell(const double *in, icFloatNumber *out)
{
  const double da = in[1] - 0.5;
  const double db = in[2] - 0.5;
  double v[4];
  v[0] = 0.5 + 2.0 * da;
  v[1] = 0.5 - 2.0 * da + 2.0 * db;
  v[2] = 0.5 - 2.0 * db;
  v[3] = 1.0 - in[0];
  for (int i = 0; i < 4; i++) {
    if (v[i] < 0.0) v[i] = 0.0;
    if (v[i] > 1.0) v[i] = 1.0;
    out[i] = (icFloatNumber)v[i];
  }
}

// Build an nIn-in / nOut-out LUT tag with identity curves either side of a CLUT
// filled by pFill.
//
// 'mft2' keeps the matrix on the input side so B is the input curve array,
// while 'mAB ' clears m_bInputMatrix so A is. Filling the wrong one writes
// nIn pointers into an nOut-pointer array.
template <class TTag>
static TTag *buildLut(icUInt8Number nGrid,
                      icUInt8Number nIn, icUInt8Number nOut,
                      icColorSpaceSignature srcSpace, icColorSpaceSignature dstSpace,
                      void (*pFill)(const double *, icFloatNumber *))
{
  TTag *pTag = new TTag();
  pTag->Init(nIn, nOut);
  pTag->SetColorSpaces(srcSpace, dstSpace);

  const bool bInputIsB = pTag->IsInputB();

  LPIccCurve *pIn = bInputIsB ? pTag->NewCurvesB() : pTag->NewCurvesA();
  for (int i = 0; i < (int)nIn; i++) {
    CIccTagCurve *pCurve = (CIccTagCurve*)CIccTag::Create(icSigCurveType);
    pCurve->SetSize(2);
    (*pCurve)[0] = 0.0f;
    (*pCurve)[1] = 1.0f;
    pIn[i] = pCurve;
  }

  CIccCLUT *pCLUT = new CIccCLUT(nIn, (icUInt16Number)nOut);
  if (!pCLUT->Init(nGrid)) {
    delete pCLUT;
    delete pTag;
    return NULL;
  }
  icFloatNumber *pData = pCLUT->GetData(0);
  for (icUInt32Number p = 0; p < pCLUT->NumPoints(); p++) {
    double in[4] = { 0.0, 0.0, 0.0, 0.0 };
    icUInt32Number rem = p;
    for (int ax = (int)nIn - 1; ax >= 0; ax--) {   // axis 0 varies slowest
      in[ax] = (double)(rem % nGrid) / (double)(nGrid - 1);
      rem /= nGrid;
    }
    pFill(in, &pData[(size_t)p * nOut]);
  }
  pTag->SetCLUT(pCLUT);

  LPIccCurve *pOut = bInputIsB ? pTag->NewCurvesA() : pTag->NewCurvesB();
  for (int i = 0; i < (int)nOut; i++) {
    CIccTagCurve *pCurve = (CIccTagCurve*)CIccTag::Create(icSigCurveType);
    pCurve->SetSize(2);
    (*pCurve)[0] = 0.0f;
    (*pCurve)[1] = 1.0f;
    pOut[i] = pCurve;
  }
  return pTag;
}

// AToB0/AToB1 and BToA0/BToA1 get identical CLUT content on purpose. A
// perceptual chain and a relative chain then differ by the PCS adjustment and
// by nothing else, which is what makes them comparable.
//
// Both directions are attached because a CMYK -> Lab -> CMYK chain needs BToA
// for its second xform, and a Lab -> CMYK chain needs it for its only one.
template <class TAtoB, class TBtoA>
static void attachLutPair(CIccProfile &p)
{
  p.AttachTag(icSigAToB0Tag, buildLut<TAtoB>(5, 4, 3, icSigCmykData, icSigLabData, cmykToLabCell));
  p.AttachTag(icSigAToB1Tag, buildLut<TAtoB>(5, 4, 3, icSigCmykData, icSigLabData, cmykToLabCell));
  p.AttachTag(icSigBToA0Tag, buildLut<TBtoA>(9, 3, 4, icSigLabData, icSigCmykData, labToCmykCell));
  p.AttachTag(icSigBToA1Tag, buildLut<TBtoA>(9, 3, 4, icSigLabData, icSigCmykData, labToCmykCell));
}

// v2 output CMYK, Lab PCS. IsVersion2() is what turns on the perceptual
// black-point adjustment, so this is the fixture for the perceptual cases.
void buildV2CmykOutputProfile(CIccProfile &p)
{
  p.InitHeader();
  p.m_Header.version     = icVersionNumberV2_1;
  p.m_Header.deviceClass = icSigOutputClass;
  p.m_Header.colorSpace  = icSigCmykData;
  p.m_Header.pcs         = icSigLabData;
  attachLutPair<CIccTagLut16, CIccTagLut16>(p);
  attachRequiredTags(p, "pcs adjust placement v2 fixture");
}

// v4 output CMYK, Lab PCS. HasPerceptualHandling() is true here, so perceptual
// gets no adjustment and only absolute intent does -- the control.
void buildV4CmykOutputProfile(CIccProfile &p)
{
  p.InitHeader();
  p.m_Header.version     = icVersionNumberV4_3;
  p.m_Header.deviceClass = icSigOutputClass;
  p.m_Header.colorSpace  = icSigCmykData;
  p.m_Header.pcs         = icSigLabData;
  attachLutPair<CIccTagLutAtoB, CIccTagLutBtoA>(p);
  attachRequiredTags(p, "pcs adjust placement v4 fixture");
}

// --- cases ----------------------------------------------------------------

// The size of the adjustment is the whole oracle: if it is smaller than the
// tolerance band, every other assertion in this file is vacuous.
static void adjustmentIsLargerThanTheToleranceBand()
{
  const double perceptualScale = 1.0 - icPerceptualRefBlackY / icPerceptualRefWhiteY;
  check(std::fabs(1.0 - perceptualScale) > 100.0 * kTol,
        "v2 perceptual adjustment is at least 100x the 1e-5 tolerance band");
}

// Trailing PCS edge: CMYK -> Lab, one profile.
static void trailingEdgeAdjustmentApplies(icRenderingIntent nIntent,
                                          bool bExpectAdjust,
                                          const char *label)
{
  CIccProfile v2;
  buildV2CmykOutputProfile(v2);

  icFloatNumber cmyk[4] = { 0.1f, 0.2f, 0.3f, 0.4f };
  icFloatNumber withIntent[3] = { 0 }, relative[3] = { 0 };

  {
    CIccCmm cmm(icSigCmykData, icSigLabData, true);
    check(cmm.AddXform(v2, nIntent) == icCmmStatOk, "trailing: AddXform");
    check(cmm.Begin() == icCmmStatOk, "trailing: Begin");
    check(cmm.Apply(withIntent, cmyk) == icCmmStatOk, "trailing: Apply");
  }
  {
    // icRelativeColorimetric on a v2 profile takes no adjustment, so it is the
    // unadjusted reference the adjusted result must differ from.
    CIccCmm cmm(icSigCmykData, icSigLabData, true);
    check(cmm.AddXform(v2, icRelativeColorimetric) == icCmmStatOk, "trailing: ref AddXform");
    check(cmm.Begin() == icCmmStatOk, "trailing: ref Begin");
    check(cmm.Apply(relative, cmyk) == icCmmStatOk, "trailing: ref Apply");
  }

  const bool moved = !closeRel(withIntent[0], relative[0], kTol);
  if (bExpectAdjust)
    check(moved, label);
  else
    check(!moved, label);
}

// Interior PCS connection: CMYK -> Lab -> CMYK, two profiles, same intent both
// ways. The two adjustments are exact inverses and adjacent in the PCS, so the
// round trip must equal the same round trip run with no adjustment at all.
static void interiorAdjustmentsCancel()
{
  CIccProfile v2a, v2b, v2c, v2d;
  buildV2CmykOutputProfile(v2a);
  buildV2CmykOutputProfile(v2b);
  buildV2CmykOutputProfile(v2c);
  buildV2CmykOutputProfile(v2d);

  icFloatNumber cmyk[4] = { 0.1f, 0.2f, 0.3f, 0.4f };
  icFloatNumber perceptual[4] = { 0 }, relative[4] = { 0 };

  {
    CIccCmm cmm(icSigCmykData, icSigCmykData, true);
    check(cmm.AddXform(v2a, icPerceptual) == icCmmStatOk, "interior: AddXform 1");
    check(cmm.AddXform(v2b, icPerceptual) == icCmmStatOk, "interior: AddXform 2");
    check(cmm.Begin() == icCmmStatOk, "interior: Begin");
    check(cmm.Apply(perceptual, cmyk) == icCmmStatOk, "interior: Apply");
  }
  {
    CIccCmm cmm(icSigCmykData, icSigCmykData, true);
    check(cmm.AddXform(v2c, icRelativeColorimetric) == icCmmStatOk, "interior: ref AddXform 1");
    check(cmm.AddXform(v2d, icRelativeColorimetric) == icCmmStatOk, "interior: ref AddXform 2");
    check(cmm.Begin() == icCmmStatOk, "interior: ref Begin");
    check(cmm.Apply(relative, cmyk) == icCmmStatOk, "interior: ref Apply");
  }

  // Both chains use AToB0/BToA0 vs AToB1/BToA1 respectively, but this fixture
  // gives both intents the same CLUT, so the only possible difference is the
  // adjustment -- and it must cancel.
  bool same = true;
  for (int i = 0; i < 4; i++)
    same = same && closeRel(perceptual[i], relative[i], kTol);
  check(same,
        "interior: perceptual round trip equals relative round trip "
        "(the two PCS adjustments cancel)");
}

// Connect() reports the cancellation directly: with the same profile and intent
// on both sides, every pushed step folds away and Connect returns identity.
static void connectReportsIdentityWhenAdjustmentsCancel()
{
  CIccProfile *pIn  = new CIccProfile();
  CIccProfile *pOut = new CIccProfile();
  buildV2CmykOutputProfile(*pIn);
  buildV2CmykOutputProfile(*pOut);

  // CIccXform::Create takes ownership of the profile it is given.
  CIccXform *pFrom = CIccXform::Create(pIn,  true,  icPerceptual, icInterpTetrahedral);
  CIccXform *pTo   = CIccXform::Create(pOut, false, icPerceptual, icInterpTetrahedral);
  check(pFrom != NULL && pTo != NULL, "connect: xforms created");
  if (!pFrom || !pTo) { delete pFrom; delete pTo; return; }

  pFrom->Begin();
  pTo->Begin();

  // This is what CheckPCSConnections() does before calling Connect().
  pFrom->SetDstPCSConversion(false);
  pTo->SetSrcPCSConversion(false);

  CIccPcsXform pcs;
  const icStatusCMM rv = pcs.Connect(pFrom, pTo);
  check(rv == icCmmStatIdentityXform,
        "connect: matched perceptual adjustments fold to icCmmStatIdentityXform");

  delete pFrom;
  delete pTo;
}

int main(int /*argc*/, char ** /*argv*/)
{
  adjustmentIsLargerThanTheToleranceBand();

  trailingEdgeAdjustmentApplies(icPerceptual, true,
      "trailing edge: v2 perceptual result differs from the unadjusted reference");
  trailingEdgeAdjustmentApplies(icAbsoluteColorimetric, true,
      "trailing edge: absolute result differs from the unadjusted reference");
  trailingEdgeAdjustmentApplies(icRelativeColorimetric, false,
      "trailing edge: relative result is the unadjusted reference");

  interiorAdjustmentsCancel();
  connectReportsIdentityWhenAdjustmentsCancel();

  if (g_failures) {
    std::printf("\n%d check(s) failed\n", g_failures);
    return 1;
  }
  std::printf("\nall checks passed\n");
  return 0;
}
